# Generated by Django 3.0.8 on 2020-08-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20200814_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='q_ans',
            field=models.TextField(),
        ),
    ]
